stages:
  - test
  - deploy

before_script:
  - apt-get update
  - python --version
  - pip3 install -r requirements.txt -r requirements-dev.txt

test inmemory:
  image: "python:3.10-bullseye"
  stage: test
  interruptible: true
  script:
    - ./test.sh --extended --backend inmemory
  coverage: '/TOTAL.*\s+(\d+%)$/'

test sqlite:
  image: "python:3.10-bullseye"
  stage: test
  interruptible: true
  script:
    - ./test.sh --extended --backend sqlite
  coverage: '/TOTAL.*\s+(\d+%)$/'

pages:
  image: "python:3.10-bullseye"
  stage: deploy
  script:
    - pip3 install -r requirements-doc.txt
    - ./build-docs.sh
    - mv docs/target/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - feature-refactor
